timeframe: "15m"
analysis_interval_minutes: 30
pairs:
  - EURUSD
  - GBPUSD
  - USDCHF
  - USDJPY
  - USDCAD
  - AUDUSD
  - XAUUSD
  - BTCUSD
risk_rules:
  max_position_pct: 2
  max_leverage: 3
  rr_targets:
    T1: 1.0
    T2: 1.5
    T3: 2.5
telegram:
  enable: true
format:
  utc: true
  price_precision: 5
