name: Test Telegram Send

on:
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Send Telegram Message
        run: |
          python3 -c "
import os, requests
token = os.getenv('TELEGRAM_BOT_TOKEN')
chat_id = os.getenv('TELEGRAM_CHAT_ID')
msg = '🚨 Teste via GitHub Actions funcionando!'
url = f'https://api.telegram.org/bot{token}/sendMessage'
r = requests.post(url, data={'chat_id': chat_id, 'text': msg})
print('Status:', r.status_code)
print('Resposta:', r.text)
"
